// story: e03s04
package plugins

import (
	"os"
	"strings"
	"testing"

	"github.com/danielvm-git/big-release/internal/algorithm"
)

func TestChangelogPluginName(t *testing.T) {
	t.Run("SC-e03s04-P1-01: Name returns 'changelog'", func(t *testing.T) {
		p := NewChangelogPlugin()
		if name := p.Name(); name != "changelog" {
			t.Errorf("expected Name() == %q, got %q", "changelog", name)
		}
	})
}

func TestChangelogPluginVerifyConditions(t *testing.T) {
	t.Run("SC-e03s04-P1-02: VerifyConditions returns nil", func(t *testing.T) {
		if err := NewChangelogPlugin().VerifyConditions(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{}); err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
	})
}

func TestChangelogPluginAnalyzeCommits(t *testing.T) {
	t.Run("SC-e03s04-P1-03: AnalyzeCommits returns empty", func(t *testing.T) {
		rt, err := NewChangelogPlugin().AnalyzeCommits(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{})
		if err != nil || rt != "" {
			t.Errorf("expected empty, got err=%v rt=%q", err, rt)
		}
	})
}

func TestChangelogPluginGenerateNotes(t *testing.T) {
	p := NewChangelogPlugin()
	t.Run("SC-e03s04-P1-04: returns empty with nil NextRelease", func(t *testing.T) {
		notes, err := p.GenerateNotes(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{NextRelease: nil})
		if err != nil || notes != "" {
			t.Errorf("expected empty, got err=%v notes=%q", err, notes)
		}
	})
	t.Run("returns empty — notes are generated by orchestrator, not this plugin", func(t *testing.T) {
		// ChangelogPlugin.GenerateNotes returns empty string because the
		// orchestrator already generates notes via algorithm.Generator.
		// Returning state.NextRelease.Notes here caused duplication
		// (BUG-changelog-duplicate-notes).
		notes, err := p.GenerateNotes(&algorithm.ReadOnlyContext{
			Commits: []*algorithm.Commit{
				{Type: "feat", Subject: "add login"},
			},
		}, &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "2.0.0", Notes: "some notes"},
		})
		if err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
		if notes != "" {
			t.Errorf("expected empty notes, got: %s", notes)
		}
	})
	t.Run("returns empty when Notes is empty", func(t *testing.T) {
		notes, err := p.GenerateNotes(&algorithm.ReadOnlyContext{
			Commits: []*algorithm.Commit{},
		}, &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "1.0.0", Notes: ""},
		})
		if err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
		if notes != "" {
			t.Errorf("expected empty notes, got: %s", notes)
		}
	})
}

func TestChangelogPluginPrepare(t *testing.T) {
	p := NewChangelogPlugin()
	t.Run("SC-e03s04-P1-10: does nothing in dry-run mode", func(t *testing.T) {
		ctx := &algorithm.ReadOnlyContext{DryRun: true}
		state := &algorithm.MutableState{NextRelease: &algorithm.Release{Version: "1.0.0", Notes: "test"}}
		if err := p.Prepare(ctx, state); err != nil {
			t.Errorf("expected no error in dry-run, got: %v", err)
		}
	})
	t.Run("SC-e03s04-P1-11: creates new CHANGELOG.md when none exists", func(t *testing.T) {
		defer chdirTempDir(t)()
		ctx := &algorithm.ReadOnlyContext{}
		state := &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "1.0.0", Notes: "### Added\n\n- feat: initial release\n"},
		}
		if err := p.Prepare(ctx, state); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		data, _ := os.ReadFile("CHANGELOG.md")
		content := string(data)
		for _, want := range []string{
			"# Changelog",
			"keepachangelog.com/en/1.1.0",
			"## [Unreleased]",
			"<!-- big-release managed -->",
			"## [1.0.0] - ",
			"### Added",
		} {
			if !strings.Contains(content, want) {
				t.Errorf("expected %q in Keep-a-Changelog file, got:\n%s", want, content)
			}
		}
		// Title and Unreleased must precede the version section.
		if strings.Index(content, "# Changelog") > strings.Index(content, "## [1.0.0]") {
			t.Errorf("title must precede version section:\n%s", content)
		}
		if strings.Index(content, "## [Unreleased]") > strings.Index(content, "## [1.0.0]") {
			t.Errorf("Unreleased must precede version section:\n%s", content)
		}
	})
	t.Run("SC-e03s04-P1-12: appends to existing CHANGELOG.md", func(t *testing.T) {
		defer chdirTempDir(t)()
		_ = os.WriteFile("CHANGELOG.md", []byte("# Changelog\n\nAll notable changes.\n\n## [Unreleased]\n\n- WIP note\n\n<!-- big-release managed -->\n\n## [0.9.0] - 2024-01-01\n\n### Added\n\n- feat: initial\n"), 0644)
		ctx := &algorithm.ReadOnlyContext{}
		state := &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "1.0.0", Notes: "### Added\n\n- feat: major release\n"},
		}
		if err := p.Prepare(ctx, state); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		data, _ := os.ReadFile("CHANGELOG.md")
		content := string(data)
		if !strings.Contains(content, "[1.0.0]") || !strings.Contains(content, "[0.9.0]") {
			t.Errorf("expected both versions in changelog, got: %s", content)
		}
		if !strings.Contains(content, "## [Unreleased]") || !strings.Contains(content, "- WIP note") {
			t.Errorf("expected Unreleased section preserved, got: %s", content)
		}
		// New release inserts above the previous version.
		if strings.Index(content, "[1.0.0]") > strings.Index(content, "[0.9.0]") {
			t.Errorf("new version must appear before older version:\n%s", content)
		}
	})
	t.Run("SC-e03s04-P1-13: uses pre-computed notes from orchestrator", func(t *testing.T) {
		defer chdirTempDir(t)()
		ctx := &algorithm.ReadOnlyContext{}
		state := &algorithm.MutableState{
			NextRelease: &algorithm.Release{
				Version: "1.0.0",
				Notes:   "### Added\n\n- feat: new feature",
			},
		}
		if err := p.Prepare(ctx, state); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		data, _ := os.ReadFile("CHANGELOG.md")
		content := string(data)
		if !strings.Contains(content, "[1.0.0]") || !strings.Contains(content, "new feature") {
			t.Errorf("expected version header and commit in changelog, got: %s", content)
		}
	})
	t.Run("BUG-changelog-title: custom changelogTitle in config", func(t *testing.T) {
		defer chdirTempDir(t)()
		ctx := &algorithm.ReadOnlyContext{
			Config: &algorithm.Config{ChangelogTitle: "Release History"},
		}
		state := &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "2.0.0", Notes: "### Added\n\n- feat: item\n"},
		}
		if err := p.Prepare(ctx, state); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		data, _ := os.ReadFile("CHANGELOG.md")
		content := string(data)
		if !strings.Contains(content, "# Release History") {
			t.Errorf("expected custom title, got: %s", content)
		}
	})
	t.Run("BUG-changelog-title: Configure changelogTitle overrides default", func(t *testing.T) {
		defer chdirTempDir(t)()
		plugin := NewChangelogPlugin()
		if err := plugin.Configure(map[string]interface{}{"changelogTitle": "My Changes"}); err != nil {
			t.Fatalf("Configure: %v", err)
		}
		state := &algorithm.MutableState{
			NextRelease: &algorithm.Release{Version: "1.0.0", Notes: "### Fixed\n\n- fix: bug\n"},
		}
		if err := plugin.Prepare(&algorithm.ReadOnlyContext{}, state); err != nil {
			t.Fatalf("Prepare: %v", err)
		}
		data, _ := os.ReadFile("CHANGELOG.md")
		content := string(data)
		if !strings.Contains(content, "# My Changes") {
			t.Errorf("expected Configure title, got: %s", content)
		}
	})
}

func TestChangelogPluginLifecycle(t *testing.T) {
	p := NewChangelogPlugin()
	t.Run("SC-e03s04-P1-14: Publish returns nil", func(t *testing.T) {
		release, err := p.Publish(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{})
		if err != nil || release != nil {
			t.Errorf("expected nil, got err=%v release=%v", err, release)
		}
	})
	t.Run("SC-e03s04-P1-15: Success returns nil", func(t *testing.T) {
		if err := p.Success(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{}); err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
	})
	t.Run("SC-e03s04-P1-16: Fail returns nil", func(t *testing.T) {
		if err := p.Fail(&algorithm.ReadOnlyContext{}, &algorithm.MutableState{}, nil); err != nil {
			t.Errorf("expected no error, got: %v", err)
		}
	})
}

// --- BUG-nil-panic-analyzer: V1 ---
func TestResolveNotes_NilNextRelease(t *testing.T) {
	// resolveNotes must not panic when NextRelease is nil.
	p := NewChangelogPlugin()
	ctx := &algorithm.ReadOnlyContext{
		Commits: []*algorithm.Commit{
			{Type: "feat", Subject: "add feature", Message: "feat: add feature"},
		},
	}
	state := &algorithm.MutableState{NextRelease: nil}

	notes, err := p.resolveNotes(ctx, state)
	if err != nil {
		t.Fatalf("expected no error, got: %v", err)
	}
	if notes != "" {
		t.Errorf("expected empty notes when NextRelease is nil, got: %q", notes)
	}
}

// --- BUG-nil-panic-analyzer: V7 ---
func TestPrepare_NilNextRelease_NoPanic(t *testing.T) {
	// Prepare must not panic when NextRelease is nil (full flow).
	p := NewChangelogPlugin()
	defer chdirTempDir(t)()
	ctx := &algorithm.ReadOnlyContext{}
	state := &algorithm.MutableState{NextRelease: nil}

	err := p.Prepare(ctx, state)
	if err != nil {
		t.Fatalf("expected no error, got: %v", err)
	}
	// Should not create a CHANGELOG.md when there's nothing to write
	_, statErr := os.Stat("CHANGELOG.md")
	if statErr == nil {
		t.Log("CHANGELOG.md was created (acceptable)")
	}
}

func TestChangelogPluginAutoRegistration(t *testing.T) {
	t.Run("SC-e03s04-P1-17: ChangelogPlugin auto-registered in global registry", func(t *testing.T) {
		found := false
		for _, name := range List() {
			if name == "changelog" {
				found = true
				break
			}
		}
		if !found {
			t.Error("expected 'changelog' to be registered in global registry")
		}
	})
}
