// story: e03s04
// bug: BUG-changelog-format BUG-changelog-title
package plugins

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/danielvm-git/big-release/internal/algorithm"
)

// managedMarker separates the hand-edit surface (title, preamble, Unreleased)
// from release-managed version sections below.
const managedMarker = "<!-- big-release managed -->"

// ChangelogPlugin generates CHANGELOG.md.
type ChangelogPlugin struct {
	title string // optional override from Configure; empty → use config/default
}

// NewChangelogPlugin creates a new ChangelogPlugin.
func NewChangelogPlugin() *ChangelogPlugin {
	return &ChangelogPlugin{}
}

// Configure decodes changelogTitle from PluginConfigs["changelog"].
// Implements ConfigurablePlugin. Default remains "# Changelog".
func (p *ChangelogPlugin) Configure(raw map[string]interface{}) error {
	if len(raw) == 0 {
		return nil
	}
	if t, ok := raw["changelogTitle"].(string); ok {
		p.title = strings.TrimSpace(t)
	}
	return nil
}

// Name returns the plugin name.
func (p *ChangelogPlugin) Name() string {
	return "changelog"
}

// VerifyConditions verifies pre-release conditions.
func (p *ChangelogPlugin) VerifyConditions(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) error {
	return nil
}

// AnalyzeCommits analyzes commits and returns release type.
func (p *ChangelogPlugin) AnalyzeCommits(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) (algorithm.ReleaseType, error) {
	return "", nil
}

// VerifyRelease is not applicable for the changelog plugin.
func (p *ChangelogPlugin) VerifyRelease(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) error {
	return nil
}

// GenerateNotes returns empty string — the changelog plugin does not
// contribute additional notes. Release notes are generated by the algorithm
// Generator in the orchestrator and written to CHANGELOG.md in Prepare().
// Returning state.NextRelease.Notes here caused duplication because the
// orchestrator already set it (BUG-changelog-duplicate-notes).
func (p *ChangelogPlugin) GenerateNotes(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) (string, error) {
	return "", nil
}

// findContentStartIdx scans existing changelog lines for the first "## " header after line 0.
func findContentStartIdx(lines []string) int {
	for i, line := range lines {
		if strings.HasPrefix(line, "## ") && i > 0 {
			return i
		}
	}
	return -1
}

// findNextH2Index returns the byte offset of the next "## " line in s, or -1.
func findNextH2Index(s string) int {
	if strings.HasPrefix(s, "## ") {
		return 0
	}
	idx := strings.Index(s, "\n## ")
	if idx < 0 {
		return -1
	}
	return idx + 1 // point at '#'
}

func normalizeTitle(title string) string {
	title = strings.TrimSpace(title)
	if title == "" {
		return "# Changelog"
	}
	if strings.HasPrefix(title, "#") {
		return title
	}
	return "# " + title
}

func newFileChangelog(title string) string {
	return normalizeTitle(title) + "\n\n" +
		"All notable changes to this project will be documented in this file.\n\n" +
		"The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),\n" +
		"and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n" +
		"## [Unreleased]\n\n" +
		managedMarker + "\n"
}

func (p *ChangelogPlugin) changelogTitle(ctx *algorithm.ReadOnlyContext) string {
	if p.title != "" {
		return p.title
	}
	if ctx != nil && ctx.Config != nil && ctx.Config.ChangelogTitle != "" {
		return ctx.Config.ChangelogTitle
	}
	return "Changelog"
}

func formatVersionHeader(version string, date time.Time) string {
	return fmt.Sprintf("## [%s] - %s", version, date.Format("2006-01-02"))
}

func (p *ChangelogPlugin) wrapReleaseNotes(state *algorithm.MutableState, notes string) string {
	if state.NextRelease == nil || state.NextRelease.Version == "" {
		return notes
	}
	trimmed := strings.TrimSpace(notes)
	if strings.HasPrefix(trimmed, "## [") {
		return notes
	}
	header := formatVersionHeader(state.NextRelease.Version, time.Now().UTC())
	if trimmed == "" {
		return header
	}
	return header + "\n\n" + notes
}

// insertReleaseSection places a new version section after Unreleased / the
// managed marker (or after the preamble for legacy files), preserving the
// existing body including any Unreleased notes.
func insertReleaseSection(existing, release, title string) string {
	release = strings.TrimSpace(release)
	if release == "" {
		return existing
	}

	if i := strings.Index(existing, managedMarker); i >= 0 {
		at := i + len(managedMarker)
		pre := strings.TrimRight(existing[:at], "\n")
		post := strings.TrimLeft(existing[at:], "\n")
		if post == "" {
			return pre + "\n\n" + release + "\n"
		}
		return pre + "\n\n" + release + "\n\n" + post
	}

	if i := strings.Index(existing, "## [Unreleased]"); i >= 0 {
		restStart := i + len("## [Unreleased]")
		rel := findNextH2Index(existing[restStart:])
		if rel >= 0 {
			insertAt := restStart + rel
			pre := strings.TrimRight(existing[:insertAt], "\n")
			post := strings.TrimLeft(existing[insertAt:], "\n")
			return pre + "\n\n" + release + "\n\n" + post
		}
		return strings.TrimRight(existing, "\n") + "\n\n" + release + "\n"
	}

	lines := strings.Split(existing, "\n")
	startIdx := findContentStartIdx(lines)
	if startIdx > 0 {
		pre := strings.TrimRight(strings.Join(lines[:startIdx], "\n"), "\n")
		post := strings.TrimLeft(strings.Join(lines[startIdx:], "\n"), "\n")
		return pre + "\n\n" + release + "\n\n" + post
	}

	if strings.HasPrefix(strings.TrimSpace(existing), "# ") {
		return strings.TrimRight(existing, "\n") + "\n\n" + release + "\n"
	}
	return newFileChangelog(title) + "\n" + release + "\n\n" + existing
}

func mergeChangelogContent(lastRelease string, existingContent string, title string) string {
	lastRelease = strings.TrimSpace(lastRelease)
	if existingContent == "" {
		if lastRelease == "" {
			return newFileChangelog(title)
		}
		return newFileChangelog(title) + "\n" + lastRelease + "\n"
	}
	if lastRelease == "" {
		return existingContent
	}
	return insertReleaseSection(existingContent, lastRelease, title)
}

func (p *ChangelogPlugin) resolveNotes(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) (string, error) {
	if state.NextRelease == nil {
		return "", nil
	}
	if state.NextRelease.Notes != "" {
		return state.NextRelease.Notes, nil
	}
	return p.GenerateNotes(ctx, state)
}

func (p *ChangelogPlugin) readChangelogFile() (string, error) {
	data, err := os.ReadFile("CHANGELOG.md")
	if err == nil {
		return string(data), nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	return "", fmt.Errorf("failed to read CHANGELOG.md: %w", err)
}

// Prepare writes the release notes to CHANGELOG.md.
func (p *ChangelogPlugin) Prepare(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) error {
	if ctx.DryRun {
		return nil
	}
	notes, err := p.resolveNotes(ctx, state)
	if err != nil {
		return fmt.Errorf("failed to generate release notes: %w", err)
	}
	notes = p.wrapReleaseNotes(state, notes)
	title := p.changelogTitle(ctx)
	existing, err := p.readChangelogFile()
	if err != nil {
		return err
	}
	merged := mergeChangelogContent(notes, existing, title)
	trimmed := strings.TrimSpace(merged) + "\n"
	if err := os.WriteFile("CHANGELOG.md", []byte(trimmed), 0644); err != nil {
		return fmt.Errorf("failed to write CHANGELOG.md: %w", err)
	}
	return nil
}

// Publish publishes the release.
func (p *ChangelogPlugin) Publish(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) (*algorithm.Release, error) {
	return nil, nil
}

// Success is called after successful release.
func (p *ChangelogPlugin) Success(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState) error {
	return nil
}

// Fail is called on release failure.
func (p *ChangelogPlugin) Fail(ctx *algorithm.ReadOnlyContext, state *algorithm.MutableState, err error) error {
	return nil
}

func init() {
	Register(NewChangelogPlugin())
}
